2022-01-03 at 14:57:29|INFO|Получен список каналов
2022-01-03 at 14:57:39|SUCCESS|Определены настройки веб драйвера
2022-01-03 at 14:57:39|DEBUG|Логинимся на reddit
2022-01-03 at 14:58:03|SUCCESS|Учпешно залогинились
2022-01-03 at 14:58:03|DEBUG|Переходим в канал interestingasfuck
2022-01-03 at 14:58:12|SUCCESS|Зашли в канал interestingasfuck и сформировали json
2022-01-03 at 14:58:13|SUCCESS|Завершили скачивание из канала interestingasfuck
2022-01-03 at 14:58:13|INFO|Выниваем данне json из html
2022-01-03 at 14:58:13|SUCCESS|Завершили формирование Json
2022-01-03 at 14:58:13|INFO|Начинаем писать в БД из паблика interestingasfuck
2022-01-03 at 14:58:42|SUCCESS|Закончили писать в БД из паблика interestingasfuck
2022-01-03 at 14:58:42|DEBUG|Запуск удаления файлов из БД помеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 14:58:42|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f2183f7d310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f2183e64790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if 'None' in path_file:
                 └ None

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 14:58:42|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f2183f7d310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f2183e64790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if 'None' in path_file:
                 └ None

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 14:58:42|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f2183f7d310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f2183e64790>

> File "/home/ily/tb_bot/parser_reddit.py", line 157, in redit_login
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '184517f8rmi8m081.gif'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images184517f8rmi8m081.gif'
2022-01-03 at 14:58:42|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f2183f7d310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f2183e64790>

> File "/home/ily/tb_bot/parser_reddit.py", line 157, in redit_login
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '199lp7g7lt4cu081.jpg'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images199lp7g7lt4cu081.jpg'
2022-01-03 at 15:03:54|INFO|Получен список каналов
2022-01-03 at 15:03:59|SUCCESS|Определены настройки веб драйвера
2022-01-03 at 15:04:00|DEBUG|Логинимся на reddit
2022-01-03 at 15:04:21|SUCCESS|Учпешно залогинились
2022-01-03 at 15:04:21|DEBUG|Переходим в канал interestingasfuck
2022-01-03 at 15:04:24|SUCCESS|Зашли в канал interestingasfuck и сформировали json
2022-01-03 at 15:04:26|SUCCESS|Завершили скачивание из канала interestingasfuck
2022-01-03 at 15:04:26|INFO|Выниваем данне json из html
2022-01-03 at 15:04:26|SUCCESS|Завершили формирование Json
2022-01-03 at 15:04:26|INFO|Начинаем писать в БД из паблика interestingasfuck
2022-01-03 at 15:04:33|SUCCESS|Закончили писать в БД из паблика interestingasfuck
2022-01-03 at 15:04:33|DEBUG|Запуск удаления файлов из БД помеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 15:04:33|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f3174a7a310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f3174961790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if None in path_file:
               └ None

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 15:04:33|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f3174a7a310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f3174961790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if None in path_file:
               └ None

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 15:04:33|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f3174a7a310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f3174961790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if None in path_file:
               └ '184517f8rmi8m081.gif'

TypeError: 'in <string>' requires string as left operand, not NoneType
2022-01-03 at 15:04:33|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f3174a7a310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f3174961790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if None in path_file:
               └ '199lp7g7lt4cu081.jpg'

TypeError: 'in <string>' requires string as left operand, not NoneType
2022-01-03 at 15:14:00|INFO|Получен список каналов
2022-01-03 at 15:14:12|SUCCESS|Определены настройки веб драйвера
2022-01-03 at 15:14:12|DEBUG|Логинимся на reddit
2022-01-03 at 15:14:35|SUCCESS|Учпешно залогинились
2022-01-03 at 15:14:35|DEBUG|Переходим в канал interestingasfuck
2022-01-03 at 15:14:39|SUCCESS|Зашли в канал interestingasfuck и сформировали json
2022-01-03 at 15:14:40|SUCCESS|Завершили скачивание из канала interestingasfuck
2022-01-03 at 15:14:40|INFO|Выниваем данне json из html
2022-01-03 at 15:14:41|SUCCESS|Завершили формирование Json
2022-01-03 at 15:14:41|INFO|Начинаем писать в БД из паблика interestingasfuck
2022-01-03 at 15:14:47|SUCCESS|Закончили писать в БД из паблика interestingasfuck
2022-01-03 at 15:14:47|DEBUG|Запуск удаления файлов из БД помеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 15:14:47|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f9bc8de5310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f9bc8ccc790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if path_file in None:
       └ None

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 15:14:47|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f9bc8de5310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f9bc8ccc790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if path_file in None:
       └ None

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 15:14:47|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f9bc8de5310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f9bc8ccc790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if path_file in None:
       └ '184517f8rmi8m081.gif'

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 15:14:47|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 165, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f9bc8de5310>

  File "/home/ily/tb_bot/parser_reddit.py", line 164, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f9bc8ccc790>

> File "/home/ily/tb_bot/parser_reddit.py", line 152, in redit_login
    if path_file in None:
       └ '199lp7g7lt4cu081.jpg'

TypeError: argument of type 'NoneType' is not iterable
2022-01-03 at 15:27:37|INFO|Получен список каналов
2022-01-03 at 15:27:45|SUCCESS|Определены настройки веб драйвера
2022-01-03 at 15:27:45|DEBUG|Логинимся на reddit
2022-01-03 at 15:28:07|SUCCESS|Учпешно залогинились
2022-01-03 at 15:28:07|DEBUG|Переходим в канал interestingasfuck
2022-01-03 at 15:28:12|SUCCESS|Зашли в канал interestingasfuck и сформировали json
2022-01-03 at 15:28:13|SUCCESS|Завершили скачивание из канала interestingasfuck
2022-01-03 at 15:28:13|INFO|Выниваем данне json из html
2022-01-03 at 15:28:14|SUCCESS|Завершили формирование Json
2022-01-03 at 15:28:14|INFO|Начинаем писать в БД из паблика interestingasfuck
2022-01-03 at 15:28:20|SUCCESS|Закончили писать в БД из паблика interestingasfuck
2022-01-03 at 15:28:20|DEBUG|Запуск удаления файлов из БД помеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 15:28:20|DEBUG|Нет пути к файлу
2022-01-03 at 15:28:20|DEBUG|Нет пути к файлу
2022-01-03 at 15:28:20|ERROR|Ошибка при поиске файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 168, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f132844b310>

  File "/home/ily/tb_bot/parser_reddit.py", line 167, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f1328332790>

> File "/home/ily/tb_bot/parser_reddit.py", line 155, in redit_login
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '184517f8rmi8m081.gif'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images184517f8rmi8m081.gif'
2022-01-03 at 15:28:20|ERROR|Ошибка при поиске файла: 
Traceback (most recent call last):

  File "/home/ily/tb_bot/parser_reddit.py", line 168, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f132844b310>

  File "/home/ily/tb_bot/parser_reddit.py", line 167, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck',)
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f1328332790>

> File "/home/ily/tb_bot/parser_reddit.py", line 155, in redit_login
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '199lp7g7lt4cu081.jpg'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images199lp7g7lt4cu081.jpg'
2022-01-03 at 15:31:19|INFO|Получен список каналов
2022-01-03 at 15:31:26|SUCCESS|Определены настройки веб драйвера
2022-01-03 at 15:31:26|DEBUG|Логинимся на reddit
2022-01-03 at 15:31:48|SUCCESS|Учпешно залогинились
2022-01-03 at 15:31:48|DEBUG|Переходим в канал interestingasfuck
2022-01-03 at 15:31:58|SUCCESS|Зашли в канал interestingasfuck и сформировали json
2022-01-03 at 15:31:59|SUCCESS|Завершили скачивание из канала interestingasfuck
2022-01-03 at 15:31:59|INFO|Выниваем данне json из html
2022-01-03 at 15:31:59|SUCCESS|Завершили формирование Json
2022-01-03 at 15:31:59|INFO|Начинаем писать в БД из паблика interestingasfuck
2022-01-03 at 15:32:06|SUCCESS|Закончили писать в БД из паблика interestingasfuck
2022-01-03 at 15:32:06|DEBUG|Запуск удаления файлов из БД помеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 15:32:06|DEBUG|Нет пути к файлу
2022-01-03 at 15:32:06|DEBUG|Нет пути к файлу
2022-01-06 at 14:59:12|INFO|Получен список каналов
2022-01-06 at 14:59:12|ERROR|An error has been caught in function '<module>', process 'MainProcess' (2157), thread 'MainThread' (140078971242304):
Traceback (most recent call last):

  File "/home/ripo/tb_bot/venvTb_bot/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    creationflags=self.creationflags)
                  │    └ 0
                  └ <selenium.webdriver.chrome.service.Service object at 0x7f66ab538208>
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
    │                └ False
    └ True
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ '/home/ripo/tb_bot/webdriver/chromedriver'
          │                    │          └ 'Permission denied'
          │                    └ 13
          └ <class 'OSError'>

PermissionError: [Errno 13] Permission denied: '/home/ripo/tb_bot/webdriver/chromedriver'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

> File "parser_reddit.py", line 169, in <module>
    search_reddit()
    └ <function search_reddit at 0x7f66ac4b7d90>

  File "parser_reddit.py", line 168, in search_reddit
    redit_login(username, password, redit)
    │           │         │         └ ('interestingasfuck', 'gifsthatkeepongiving', 'oddlysatisfying')
    │           │         └ 'UOgyiog8374fgboa8fgdOU6e93ced923c%^CvV'
    │           └ 'Ripozi'
    └ <function search_reddit.<locals>.redit_login at 0x7f66ab524bf8>

  File "parser_reddit.py", line 45, in redit_login
    browser = webdriver.Chrome(service=s, options=options)
              │         │              │          └ <selenium.webdriver.chrome.options.Options object at 0x7f66ab538240>
              │         │              └ <selenium.webdriver.chrome.service.Service object at 0x7f66ab538208>
              │         └ <class 'selenium.webdriver.chrome.webdriver.WebDriver'>
              └ <module 'selenium.webdriver' from '/home/ripo/tb_bot/venvTb_bot/lib/python3.7/site-packages/selenium/webdriver/__init__.py'>

  File "/home/ripo/tb_bot/venvTb_bot/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
    │                 │        └ True
    │                 └ <selenium.webdriver.chrome.service.Service object at 0x7f66ab538208>
    └ None
  File "/home/ripo/tb_bot/venvTb_bot/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
    │    │       └ <function Service.start at 0x7f66ac81b048>
    │    └ <selenium.webdriver.chrome.service.Service object at 0x7f66ab538208>
    └ <unprintable WebDriver object>
  File "/home/ripo/tb_bot/venvTb_bot/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
    │  │    │        │    │      │    └ 'Please see https://chromedriver.chromium.org/home'
    │  │    │        │    │      └ <selenium.webdriver.chrome.service.Service object at 0x7f66ab538208>
    │  │    │        │    └ '/home/ripo/tb_bot/webdriver/chromedriver'
    │  │    │        └ <selenium.webdriver.chrome.service.Service object at 0x7f66ab538208>
    │  │    └ <function basename at 0x7f66ad2b3f28>
    │  └ <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
    └ <module 'os' from '/usr/lib/python3.7/os.py'>

selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home

