2022-01-03 at 15:20:12|DEBUG|Запуск удаления файлов из БДпомеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 15:20:13|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

> File "/home/ily/tb_bot/test_11.py", line 34, in <module>
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '184517f8rmi8m081.gif'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images184517f8rmi8m081.gif'
2022-01-03 at 15:20:13|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

> File "/home/ily/tb_bot/test_11.py", line 34, in <module>
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '199lp7g7lt4cu081.jpg'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images199lp7g7lt4cu081.jpg'
2022-01-03 at 15:21:24|DEBUG|Запуск удаления файлов из БДпомеченных на удаление[(None, 4), (None, 7), ('184517f8rmi8m081.gif', 184), ('199lp7g7lt4cu081.jpg', 199)]
2022-01-03 at 15:21:24|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

> File "/home/ily/tb_bot/test_11.py", line 34, in <module>
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '184517f8rmi8m081.gif'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images184517f8rmi8m081.gif'
2022-01-03 at 15:21:24|ERROR|Ошибка при удалении файла: 
Traceback (most recent call last):

> File "/home/ily/tb_bot/test_11.py", line 34, in <module>
    os.remove(r'/home/ily/tb_bot/images' + path_file) # удаление файла
    │  │                                   └ '199lp7g7lt4cu081.jpg'
    │  └ <built-in function remove>
    └ <module 'os' from '/usr/lib/python3.8/os.py'>

FileNotFoundError: [Errno 2] No such file or directory: '/home/ily/tb_bot/images199lp7g7lt4cu081.jpg'
